version: "3.8"

services:
  ventas:
    build: ./ventas_experimento
    ports:
      - "5000:5000"
    container_name: ventas_service
    env_file:
      - ./ventas_experimento/.env
    volumes:
      - ./ventas_experimento/cloud-key.json:/app/cloud-key.json
    networks:
      - microservices_network

  bodega:
    build: ./bodega_experimento
    ports:
      - "5002:5002"
    container_name: bodega_service
    env_file:
      - ./bodega_experimento/.env
    volumes:
      - ./bodega_experimento/cloud-key.json:/app/cloud-key.json
    networks:
      - microservices_network

  jmeter:
    image: justb4/jmeter:latest
    container_name: jmeter
    volumes:
      - ./jmeter_tests:/tests
    working_dir: /tests
    command: >
      -n -t test_plan.jmx -l test_results.jtl
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge