version: "3.8"

services:
  ventas:
    build: ./ventas_experimento
    ports:
      - "5000:5000"
    container_name: ventas_service
    env_file:
      - ./ventas_experimento/.env
    volumes:
      - ./ventas_experimento:/app
      - ./ventas_experimento/cloud-key.json:/app/cloud-key.json
    networks:
      - microservices_network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

  bodega:
    build: ./bodega_experimento
    ports:
      - "5002:5002"
    container_name: bodega_service
    env_file:
      - ./bodega_experimento/.env
    volumes:
      - ./bodega_experimento:/app
      - ./bodega_experimento/cloud-key.json:/app/cloud-key.json
    networks:
      - microservices_network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5002", "--reload"]

networks:
  microservices_network:
    driver: bridge